2025-05-09 17:54:42,229 ERROR: Exception on /translate [POST] [in /home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/app/main/routes.py", line 176, in translate_text
    "text": translate(data["text"], data["source_language"], data["dest_language"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/app/translate.py", line 29, in translate
    "Ocp-Apim-Subscription-Region": app.config["MS_TRANSLATOR_LOCATION"],
                                    ^^^
NameError: name 'app' is not defined
2025-05-09 18:08:05,605 ERROR: Exception on /translate [POST] [in /home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/app/main/routes.py", line 176, in translate_text
    "text": translate(data["text"], data["source_language"], data["dest_language"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piserver/microblog/app/translate.py", line 29, in translate
    "Ocp-Apim-Subscription-Region": app.config["MS_TRANSLATOR_LOCATION"],
                                    ^^^
NameError: name 'app' is not defined
2025-05-09 18:31:36,820 INFO: Microblog startup [in /home/piserver/microblog/app/__init__.py:81]
2025-05-09 18:31:36,899 INFO: Microblog startup [in /home/piserver/microblog/app/__init__.py:81]
2025-05-09 19:26:22,604 INFO: Microblog startup [in /home/piserver/microblog/app/__init__.py:81]
2025-05-09 19:26:22,688 INFO: Microblog startup [in /home/piserver/microblog/app/__init__.py:81]
2025-05-23 02:17:24,159 INFO: Microblog startup [in /home/piserver/microblog/app/__init__.py:81]
2025-05-23 02:17:24,159 INFO: Microblog startup [in /home/piserver/microblog/app/__init__.py:81]
2025-05-26 15:22:00,174 INFO: Microblog startup [in /home/piserver/microblog/app/__init__.py:81]
2025-05-26 15:22:00,174 INFO: Microblog startup [in /home/piserver/microblog/app/__init__.py:81]
